version: ${VERSION}

services:
  appointment:
    build:
      context: ./server
      dockerfile: appointment/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    image: ${SERVICE_NAME}-appointment
    container_name: ${SERVICE_NAME}-appointment
    ports:
      - "8010:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/${SERVICE_NAME}_appointment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
  hiring:
    build:
      context: ./server
      dockerfile: hiring/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    image: ${SERVICE_NAME}-hiring
    container_name: ${SERVICE_NAME}-hiring
    ports:
      - "8020:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/${SERVICE_NAME}_hiring
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
  sso:
    container_name: ${SERVICE_NAME}-document-sso
    extends:
      file: ./infrastructure/docker-compose.infrastructure.yml
      service: sso
  kong-db:
    container_name: ${SERVICE_NAME}-document-gateway-database
    extends:
      file: ./infrastructure/gateway/docker-compose.gateway.yml
      service: kong-db
  kong:
    container_name: ${SERVICE_NAME}-document-gateway
    extends:
      file: ./infrastructure/gateway/docker-compose.gateway.yml
      service: kong
  queue:
    container_name: ${SERVICE_NAME}-document-queue
    extends:
      file: ./infrastructure/docker-compose.infrastructure.yml
      service: queue
  database:
    container_name: ${SERVICE_NAME}-document-database
    extends:
      file: ./infrastructure/docker-compose.infrastructure.yml
      service: database

volumes:
  db-volume:
  migration-volume: