version: ${VERSION}

services:
  appointment:
    build:
      context: ./server/appointment
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    image: companymanagement-appointment
    container_name: companymanagement-appointment
    ports:
      - "8010:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/company_managment_appointment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
  hiring:
    build:
      context: ./server/hiring
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    image: companymanagement-hiring
    container_name: companymanagement-hiring
    ports:
      - "8020:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/company_managment_hiring
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
  document:
    build:
        context: ./server/document
        dockerfile: Dockerfile
    depends_on:
        database:
            condition: service_healthy
    image: companymanagement-document
    container_name: companymanagement-document
    ports:
        - "8030:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/company_managment_document
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root


# Infrastructure is missing