spring:
  application:
    name: appointment

  liquibase:
    change-log: classpath:/liquibase/master-changelog.xml
    enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/company_management_appointment
    username: root
    password: wasd
    driver-class-name: org.mariadb.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      function:
        definition: generateAppointmentInterview
      bindings:
        generateAppointmentInterview-in-0:
          destination: hiring.interview.state.generated
      rabbit:
        bindings:
          generateAppointmentInterview-in-0:
            consumer:
              bindingRoutingKey: hiring.interview.state.generated
              exchangeDurable: true
              exchangeType: topic

springdoc:
  packagesToScan: cenglisch.appointment.port.adapter.primary