spring:
  application:
    name: appointment

  liquibase:
    change-log: classpath:/liquibase/master-changelog.xml
    enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/company_management_appointment
    username: root
    password: wasd
    driver-class-name: org.mariadb.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      function:
        definition: generateAppointmentInterview
      bindings:
        generateAppointmentInterview-in-0:
          binder: generateAppointmentInterview
          destination: hiring.interview.state.generated
          content-type: application/json
      binders:
        generateAppointmentInterview:
          type: rabbit
      rabbit:
        bindings:
          input:
            generateAppointmentInterview-in-0:
              consumer:
                binding-routing-key: hiring.interview.state.generated
                exchange-name: interview-exchange
                queue-name-group-only: true
                bind-queue: true
                exchange-durable: true
                exchange-type: topic

springdoc:
  packagesToScan: cenglisch.appointment.port.adapter.primary