spring:
  application:
    name: hiring

  liquibase:
    change-log: classpath:/liquibase/master-changelog.xml
    enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/company_management_hiring
    username: root
    password: wasd
    driver-class-name: org.mariadb.jdbc.Driver