spring:
  application:
    name: hiring

  liquibase:
    change-log: classpath:/liquibase/master-changelog.xml
    enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/company_management_hiring
    username: root
    password: wasd
    driver-class-name: org.mariadb.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      function:
        definition: acceptInterview;launchInterview;endInterviewExecution
      bindings:
        acceptInterview-in-0:
          destination: appointment.interview.accepted
        launchInterview-in-0:
          destination: appointment.interview.launched
        endInterviewExecution-in-0:
          destination: appointment.interview.generated
      rabbit:
        bindings:
          acceptInterview-in-0:
            consumer:
              bindingRoutingKey: appointment.interview.accepted
              exchangeDurable: true
              exchangeType: topic
          launchInterview-in-0:
            consumer:
              bindingRoutingKey: appointment.interview.launched
              exchangeDurable: true
              exchangeType: topic
          endInterviewExecution-in-0:
            consumer:
              bindingRoutingKey: appointment.interview.generated
              exchangeDurable: true
              exchangeType: topic
        default:
          producer:
            exchangeType: topic
      dynamic:
        destination: 'unused'
        binder: rabbit
        contentType: application/json

springdoc:
  packagesToScan: cenglisch.hiring.port.adapter.primary