server:
  port: 8080
  forward-headers-strategy: framework

springdoc:
  packagesToScan: cenglisch.hiring.port.adapter.primary

spring:
  application:
    name: hiring

  liquibase:
    change-log: classpath:/liquibase/master-changelog.xml
    enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/company_management_hiring
    username: root
    password: wasd
    driver-class-name: org.mariadb.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      default-binder: messagePublisher
      function:
        definition: acceptInterview;launchInterview;endInterviewExecution
      bindings:
        acceptInterview-in-0:
          binder: acceptInterview
          destination: appointment.interview.accepted
          content-type: application/json
        launchInterview-in-0:
          binder: launchInterview
          destination: appointment.interview.launched
          content-type: application/json
        endInterviewExecution-in-0:
          binder: endInterviewExecution
          destination: appointment.interview.executionEnded
          content-type: application/json
        messagePublisher-out-0:
          binder: messagePublisher
          destination: appointment.interview.message
          content-type: application/json
      binders:
        acceptInterview:
          type: rabbit
        launchInterview:
          type: rabbit
        endInterviewExecution:
          type: rabbit
        messagePublisher:
          type: rabbit
      rabbit:
        bindings:
          input:
            acceptInterview-in-0:
              consumer:
                binding-routing-key: appointment.interview.accepted
                exchange-name: appointment-interview-exchange
                queue-name-group-only: true
                bind-queue: true
                exchange-durable: true
                exchange-type: topic
            launchInterview-in-0:
              consumer:
                binding-routing-key: appointment.interview.launched
                exchange-name: appointment-interview-exchange
                queue-name-group-only: true
                bind-queue: true
                exchange-durable: true
                exchange-type: topic
            endInterviewExecution-in-0:
              consumer:
                binding-routing-key: appointment.interview.executionEnded
                exchange-name: appointment-interview-exchange
                queue-name-group-only: true
                bind-queue: true
                exchange-durable: true
                exchange-type: topic
          output:
            messagePublisher-out-0:
              producer:
                binding-routing-key: appointment.interview.message
                exchange-name: appointment-interview-exchange
                exchange-durable: true
                exchange-type: topic