spring:
  application:
    name: hiring

  liquibase:
    change-log: classpath:/liquibase/master-changelog.xml
    enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/company_management_hiring
    username: root
    password: wasd
    driver-class-name: org.mariadb.jdbc.Driver

  cloud:
    stream:
      rabbit:
        default:
          producer:
            exchangeType: topic
      dynamic:
        destination: 'unused'
        binder: rabbit
        contentType: application/json

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  packagesToScan: cenglisch.hiring.port.adapter.primary